void test_all();
void test_setteri_getteri();
void test_add_all_size();
void test_sort_delete();
void test_proprietati();
void test_service();
void test_undo();
void test_swap_repos();
void test_ui();